
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msszikayvszysbdmvvkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zc3ppa2F5dnN6eXNiZG12dmt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1NTE5OTQsImV4cCI6MjA1NjEyNzk5NH0.hOttB5JE-ScEyR9GpnPz8ctcZ7_ZCLYPYDuUEb_OYVQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a custom client type that extends the base client with our custom functions
type SupabaseClientWithCustomTypes = ReturnType<typeof createClient<Database>> & {
  rpc<T = any>(fn: 'has_role' | 'get_application_user_id' | 'is_application_draft', params?: object): Promise<{
    data: T;
    error: null;
  } | {
    data: null;
    error: any;
  }>;
};

// Create the client with the extended type
export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
) as SupabaseClientWithCustomTypes;
