
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msszikayvszysbdmvvkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zc3ppa2F5dnN6eXNiZG12dmt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1NTE5OTQsImV4cCI6MjA1NjEyNzk5NH0.hOttB5JE-ScEyR9GpnPz8ctcZ7_ZCLYPYDuUEb_OYVQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create supabase client with explicit auth settings
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage, // Explicitly use localStorage
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
  },
});

// Log when the client is initialized
console.log("[Supabase] Client initialized");

// Export a function to check connection status
export const checkSupabaseConnection = async () => {
  try {
    const { error } = await supabase.auth.getSession();
    if (error) {
      console.error("[Supabase] Connection check error:", error);
      return false;
    }
    console.log("[Supabase] Connection check successful");
    return true;
  } catch (e) {
    console.error("[Supabase] Connection check exception:", e);
    return false;
  }
};
